### ISSUE TITLE
Fix test broken in "abtesting/optimizelyXExperiment"

### ISSUE THREAD

**Issue by kikoruiz** [SUI-Components/schibsted-spain-components#69]
Fix test broken in "abtesting/optimizelyXExperiment" component

**Comment by midudev** [comment]
Fixed in master with this: https://github.com/SUI-Components/schibsted-spain-components/blob/master/jest.config.js

**Comment by midudev** [comment]
Fixed!

**Comment by midudev** [comment]
Fixed!
